config/routes.rb
Rails.application.routes.draw do
  get 'braintree/new'
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  get 'home/index'

  get 'listings/verify' => 'listings#verify', as: 'listing_pending_verification'
  post 'listings/:id/verify' => 'listings#verify!', as: 'verify_listing'
  post 'users/:id/delete_avatar' => 'users#delete_avatar', as: 'delete_avatar'
  post 'users/:id/upload_avatar' => 'users#upload_avatar', as: 'upload_avatar'
  post 'listings/:id/delete_photo' => 'listings#delete_photo', as: 'delete_photo'

  post 'listings/:listing_id/reservations/:id/payment' => 'braintree#checkout', as: 'checkout'
  get 'listings/:listing_id/reservations/:id/payment' => 'braintree#new', as: 'verify_payment'
  # get 'listings/:listing_id/reservations/:id/payment' => 'braintree#checkout', as: 'checkout'

  get 'users/:id/edit' => 'users#edit', as: 'edit_profile'
  get 'listings/:id/edit' => 'listings#edit', as: 'edit_listing'
  get "listings/search" => 'listings#search', as: 'listings_search'
  get "listings/global_search" => 'listings#global_search', as: 'global_search'
  get "listings/ajax_search" => 'listings#ajax_search', as: 'ajax_search'
  # get 'reservations/new'
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

    get "users/admin"
    get "users/profile"

    get "users/:id" => 'users#profile', as: 'user_profile'
    get "listings/confirmation" => 'listings#listing_confirmation', as: 'listing_confirmation'
    get "users/:id/delete" => 'users#destroy', as: 'delete_user'


  # get "users/:id/deletes"
  resources :articles
  resources :listings do
    # remvoed :index
    resources :reservations, only: [:index, :create, :update, :show, :delete]
  end
  resources :users

  # testing listings
  # resources :users do
  #   resources :listings
  # end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => "home#index"

end

app/models/listing.rb
class Listing < ApplicationRecord
  include PgSearch
  include Filterable

  belongs_to :user
  has_many :reservations, dependent: :destroy

  # pg_search_scope :search_by_property_title, :against => [:property_title]
  # malaysia
  pg_search_scope :search_by_listings,
                  :against => [:property_title, :location],
                  :using => {
                    :tsearch => {:prefix => true}
                  }

  mount_uploaders :photos, AvatarUploader
  validates :property_title, presence: true,
                  length: { minimum: 4 }
  validates :location, presence: true,
                  length: { minimum: 4 }
# input regex here
  validates :price, presence: true,
                  length: { minimum: 3 }
  validates :location, presence: true,
                  length: { minimum: 4 }
  validates :photos, presence: true

# scoping
  scope :property_title, -> (property_title) { where property_title: property_title }
  scope :location, -> (location) { where location: location }


  # pg_search_scope :search_by_title, :against => :title

end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  def index
    @listings = Listing.where(verify: true)
    @listings_page = @listings.page params[:page]

  end

# to refactor search -> filter
# test scoping/filtering --> to refactor to module
  def search
    @listings = Listing.where(verify: true)
    x = params[:listing][:property_title]
    y = params[:listing][:location]
    @listings = @listings.filter(property_title:x,location:y)
    @listings_page = @listings.page params[:page]
  end

  def global_search
    @listings = Listing.where(verify: true)
      if params[:listing][:term]
        @listings = @listings.search_by_listings(params[:listing][:term])
      else
        @Listings = @listings
      end
    @listings_page = @listings.page params[:page]
  end

  def ajax_search
    @listings = Listing.where(verify: true)
    @listings = Listing.search_by_listings(params["query"]).pluck(:location).uniq
    respond_to do |format|
      format.json { render json: @listings }
      format.js # remote: true is sent a js format and sends you to search.js.erb
    end
  end

  def show
    @listing = Listing.find(params[:id])
    @listings = Listing.where(verify: true)
    @reservation = Reservation.new
    @listings_page = @listings.page params[:page]
    @user = User.find(@listing.user_id)
    @host = @user
  end

  def new
    @user = current_user
    @listing = Listing.new
    # @listings = Article.all
    @user_id = User.find(current_user.id)
  end

  def edit
    @listing = Listing.find(params[:id])
    @user_id = User.find(current_user.id)
  end

  def verify
    @user_ranking = current_user.role
    @listings = Listing.where(verify:true)
    @listings_page = Listing.order(:location).page params[:page]
    @user_id = User.find(current_user.id)
  end

  def verify!
    @listing = Listing.find(params[:id])
    @listing.update(verify: true)
    redirect_to listing_pending_verification_path
  end

  def create

    @listing = Listing.new(listing_params)
    @listing.user_id = current_user.id
    @user = User.find(@listing.user_id)

    if @listing.save
      redirect_to listing_confirmation_path
    else
      render 'new'
    end
    end

  def update
  @listing = Listing.find(params[:id])
    if @listing.update(listing_params)
      redirect_to @listing
    else
      render 'edit'
    end
end

  def destroy
    @listing = Listing.find(params[:id])
    @listing.destroy
    redirect_to root_path
  end

  def delete_photo
    @listing = Listing.find(params[:id])
    @listing.remove_photos!
    @listing.save
    redirect_to root_path
  end

  private
    def listing_params
      params.require(:listing).permit(:property_title, :location, :price, :description, :user_id, {photos:[]}, :room_number, :bed_number, :guest_number, :country, :state, :city, :zipcode, :address)
    end
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_form.html.erb
<%= form_with model: @listing, local: true do |form| %>

  <% if @listing.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@listing.errors.count, "error") %> prohibited
        this listing from being saved:
      </h2>
      <ul>
        <% @listing.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :property_title %><br>
    <%= form.text_field :property_title %>
  </p>

  <p>
    <%= form.label :location %><br>
    <%= form.text_area :location %>
  </p>

    <p>
      <%= form.label :price %><br>
      <%= form.text_area :price %>
    </p>

    <p>
      <%= form.label :description %><br>
      <%= form.text_area :description %>
    </p>
    <p>
      <%= form.label :country %><br>
      <%= form.text_area :country %>
    </p>
    <p>
      <%= form.file_field :photos, multiple: true %>
    </p>

    <p>
      <%= form.submit %>
    </p>

<% end %>

app/views/listings/_listings.html.erb
<% @listings_page.each do |listing| %>
  <% if listing.verify == true %>
  <div class="card-deck grow1">
      <div class="card">
          <div class="card-body">
            <% if listing.photos[0] == nil %>
            <a href="/listings/<%=listing.id%>">
            <%= image_tag ("No_Image_Available.png"), :class => "card-img-top"%>
            </a>
            <% else -%>
            <a href="/listings/<%=listing.id%>">
            <%= image_tag listing.photos.first.url, :class => "card-img-top"%>
            </a>
            <% end %>
            <h5 class="card-title"><%= listing.property_title %></h5>
            <p class="card-text"><%= listing.price %></p>
            <p class="card-text"><%= listing.location %></p>
            <a href="#" class="btn btn-primary"> <%= link_to 'Details', listing_path(listing) %> </a>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>
<div class="pagination">
<%= paginate @listings_page %>
</div>

app/views/listings/ajax_search.js.erb
$("#list").html();
<% @listings.each do |city| %>
  var option = document.createElement("option");
  option.value = "<%= city %>";

  //append option to list
  $("#list").append(option);
<% end %>

app/views/listings/edit.html.erb
<h1>Edit Listing</h1>

<%= render 'form' %>

<%= link_to 'Back', listings_path %>

app/views/listings/global_search.html.erb
<%= render partial: "shared/navbar" %>
<% @listings.each do |listing| %>
  <% if listing.verify == true %>
    <div class="card-deck grow1">
        <div class="card">
          <div class="card-body">
              <% if listing.photos[0] == nil %>
                  <%= image_tag  ("No_Image_Available.png"), :class => "card-img-top"%>
              <% else -%>
              <a href="/listings/<%=listing.id%>">
                <%= image_tag listing.photos.first.url, :class => "card-img-top"%>
              </a>
              <% end %>
              <h5 class="card-title"><%= listing.property_title %></h5>
              <p class="card-text"><%= listing.price %></p>
              <p class="card-text"><%= listing.location %></p>
              <%= link_to 'Details', listing_path(listing) %>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>

app/views/listings/index.html.erb
  <!-- search form -->
<!-- access to admin page for admin and above -->
<% if signed_in? -%>
    <%= render partial: "shared/navbar" %>
  <% else -%>
    <%= render partial: "shared/navbar_guest" %>
<% end -%>

<% if signed_in? -%>
  <% if current_user.role == "moderator"||current_user.role == "superadmin"-%>
    <p>Authorization level: <%= current_user.role.capitalize %> <a href="listings/verify">[Administration Page Here]</a></p>
  <% end -%>
<% end -%>
<div class="all_decks">
  <%= render 'shared/listings' %>
</div>

app/views/listings/listing_confirmation.html.erb
<h3>Confirmation Form</h3>
  <p>Dear <%=current_user.full_name%>, your listing has been submitted and
     currently pending approval by CoolStay's management within 24 hours.
     Thank You for choosing us and have a nice day :)
  </p>

  <%= link_to 'Back', root_path %>

app/views/listings/new.html.erb
<%= render 'shared/navbar_no_search' %>
<h3>New Listing form</h3>
<%= form_with model: @listing, url: listings_path, local: true do |form| %>
<% if @listing.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@listing.errors.count, "error") %> prohibited
      this listing from being saved:
    </h2>
    <ul>
      <% @listing.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<div class="create_listing">
  <form>
    <div class="form-group">
      <%= form.label :property_title, class: "col-sm-2 col-form-label" %>
      <div class="col-sm-10">
        <%= form.text_field :property_title, class:"form-control" %>
      </div>
    </div>

    <div class="form-group">
      <%= form.label :location, class: "col-sm-1 col-form-label" %>
      <div class="col-sm-10">
        <%= form.text_field :location, class:"form-control"  %>
      </div>
    </div>

    <div class="form-group">
      <%= form.label :country, class: "col-sm-1 col-form-label" %>
      <div class="col-sm-10">
        <%= form.text_field :country, class:"form-control"  %>
      </div>
    </div>

    <div class="form-group">
      <%= form.label :price, class: "col-sm-1 col-form-label" %>
      <div class="col-sm-10">
        <%= form.text_field :price, class:"form-control"  %>
      </div>
    </div>

    <div class="form-group">
      <%= form.label :description, class: "col-sm-1 col-form-label" %>
      <div class="col-sm-10">
        <%= form.text_field :description, class:"form-control"  %>
      </div>
    </div>

    <div class='align_center'>
      <%= form.file_field :photos, multiple: true, class:"file-uploader" %><br><br>
      <%= form.submit class:"btn btn-primary" %>
    </div>

  </form>
</div>
<% end %>

app/views/listings/search.html.erb
<%= render 'shared/navbar' %>

<% @listings.each do |listing| %>
  <% if listing.verify == true %>
      <div class="d-flex flex-row">
        <div class="p-2">
          <div class="card" style="width: 18rem;">
            <div class="card-body">
              <% if listing.photos[0] == nil %>
                <%= image_tag  ("No_Image_Available.png"), :class => "card-img-top"%>
              <% else -%>
                <%= image_tag listing.photos.first.url, :class => "card-img-top"%>
              <% end %>
              <h5 class="card-title"><%= listing.property_title %></h5>
              <p class="card-text"><%= listing.price %></p>
              <p class="card-text"><%= listing.location %></p>
              <p class="card-text"><%= listing.description %></p>
              <a href="#" class="btn btn-primary"><%= link_to 'Show', listing_path(listing) %></a>
            </div>
          </div>
        </div>
      </div>
    <% end %>
<% end %>

app/views/listings/show.html.erb
<%= render partial: "shared/navbar_no_search" %>
<link href="//netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<div class='show-content'>
	<div class='content-top'>
		<div id="myCarousel" class="carousel slide">
	    <ol class="carousel-indicators">
	        <li data-target="#myCarousel" data-slide-to="0" class="" contenteditable="false"></li>
	        <li data-target="#myCarousel" data-slide-to="1" class="active" contenteditable="false"></li>
	        <li data-target="#myCarousel" data-slide-to="2" class="" contenteditable="false"></li>
	    </ol>
	    <div class="carousel-inner">
	      <div class="item active">
	          <%= image_tag @listing.photos[Random.rand(@listing.photos.length)].url, class: "listing-image"%>
	      </div>

	      <% @listing.photos.each.with_index do |listing,index| %>

	        <div class="item" style="">
	                <%= image_tag @listing.photos[index].url,class: "listing-image" %>
	        </div>
	      <% end -%>
	        <div class="item" style="">
	            <%= image_tag @listing.photos[0].url, class: "listing-image"%>
	        </div>
	    </div>

	    <a class="left carousel-control" href="#myCarousel" data-slide="prev">
	        <span class="glyphicon glyphicon-chevron-left"></span>
	    </a>

	    <a class="right carousel-control" href="#myCarousel" data-slide="next">
	        <span class="glyphicon glyphicon-chevron-right"></span>
	    </a>
		</div><br>
		<!-- carousel ended -->
		<p>
			<strong>Hosted by:</strong>
			<%= @host.full_name %>
		</p>
	</div>
<div class="listing-body">
		  <% if signed_in? %>
		    <% if current_user.id == @listing.user_id && @listing.photos? == true %>
		      <td><%= link_to 'Update Listing', edit_listing_path(@listing) %></td>
		      <td><%= link_to 'Delete', delete_photo_path(@listing.id),
		      method: :post,
		      data: { confirm: 'Are you sure?' } %></tr>
		    <% end -%>
		  <% end -%>
	<div class="listing-content">
		<h2><%= @listing.property_title %></h2>
		  <h2>Description</h2>
			<p>
		  	<%= @listing.description %>
			</p>
			<p>
				<%= @listing.location %>
			</p>
			<p>
			  USD<%= @listing.price %> per night
			</p>
			<!-- Datepicker Start -->
				<div class="date-selection">
						<%= form_with scope: :reservation, url: listing_reservations_path(@listing.id), local: true do |form| %>
						<%= form.text_field :start_date, {class: 'datepicker', placeholder:'Check-in',autocomplete:"off"} %>
							<script type="text/javascript">
								$(document).ready(function(){
									$('.datepicker').datepicker();
								});
							</script>
							<%= form.text_field :end_date, {class: 'datepicker', placeholder:'Check-out', autocomplete:"off"} %>
							<script type="text/javascript">
								$(document).ready(function(){
									$('.datepicker').datepicker();
								});
							</script>
							<p>
								<%= form.submit "Reserve" %>
							</p>
							<% if @reservation.errors.any?%>
							<div id="error_explanation">
								<h2>
									<%= pluralize(@reservation.errors.count, "error") %> prohibited
									this reservation from being saved:
								</h2>
								<ul>
									<% @reservation.errors.full_messages.each do |msg| %>
										<li><%= msg %></li>
									<% end %>
								</ul>
							</div>
						<% end %>
					<% if signed_in? %>
						<% if current_user.id == @listing.user_id && @listing.photos? == true %>
								<p><%= link_to 'Delete this property', listing_path(@listing.id),
														method: :delete,
														data: { confirm: 'Are you sure?' } %>
								</p>
						 <% end -%>
					 <% end -%>
					<% end %>
			</div>
	</div>

		<%= link_to 'Back', listings_path %>
</div>

app/views/listings/verify.html.erb
<%= render 'shared/navbar' %>

<% if current_user.role == "moderator" || current_user.role == "superadmin" -%>
  <p>You are <%= @user_ranking.capitalize %></p>
  <%= paginate @listings_page %>
  <table>
    <% if @listings == nil %>

    <% else %>
      <% @listings_page.each do |listing| %>
        <% if listing.verify == false %>
          <tr>
            <th>ID</th>
            <th>Title</th>
            <th>Price</th>
            <th>Location</th>
            <th>Description</th>
            <th colspan="4">Action</th>
          </tr>
          <tr>
            <td><%= listing.id %></td>
            <td><%= listing.property_title %></td>
            <td><%= listing.price %></td>
            <td><%= listing.location %></td>
            <td><%= listing.description %></td>
            <td><%= link_to 'Show', listing_path(listing) %></td>
            <td><%= link_to 'Edit', edit_listing_path(listing) %></td>
            <td><%= link_to 'Destroy', listing_path(listing),
                    method: :delete,
                    data: { confirm: 'Are you sure?' } %></td>
              <td><%= link_to 'Verify', verify_listing_path(listing),
              method: 'POST'%></td>
          </tr>
        <% end %>
      <% end %>
    <% end %>
  </table>
<% else -%>
  <p>You are not Authorized to access this page please go
  <%= link_to 'Back', listings_path %></p>

<% end -%>

app/views/listings/verify_payment.html.erb
<%= render 'navbar' %>