config/routes.rb
Rails.application.routes.draw do
  get 'braintree/new'
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  get 'home/index'

  get 'listings/verify' => 'listings#verify', as: 'listing_pending_verification'
  post 'listings/:id/verify' => 'listings#verify!', as: 'verify_listing'
  post 'users/:id/delete_avatar' => 'users#delete_avatar', as: 'delete_avatar'
  post 'users/:id/upload_avatar' => 'users#upload_avatar', as: 'upload_avatar'
  post 'listings/:id/delete_photo' => 'listings#delete_photo', as: 'delete_photo'

  post 'listings/:listing_id/reservations/:id/payment' => 'braintree#checkout', as: 'checkout'
  get 'listings/:listing_id/reservations/:id/payment' => 'braintree#new', as: 'verify_payment'
  # get 'listings/:listing_id/reservations/:id/payment' => 'braintree#checkout', as: 'checkout'

  get 'users/:id/edit' => 'users#edit', as: 'edit_profile'
  get 'listings/:id/edit' => 'listings#edit', as: 'edit_listing'
  get "listings/search" => 'listings#search', as: 'listings_search'
  get "listings/global_search" => 'listings#global_search', as: 'global_search'
  get "listings/ajax_search" => 'listings#ajax_search', as: 'ajax_search'
  # get 'reservations/new'
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

    get "users/admin"
    get "users/profile"

    get "users/:id" => 'users#profile', as: 'user_profile'
    get "listings/confirmation" => 'listings#listing_confirmation', as: 'listing_confirmation'
    get "users/:id/delete" => 'users#destroy', as: 'delete_user'


  # get "users/:id/deletes"
  resources :articles
  resources :listings do
    # remvoed :index
    resources :reservations, only: [:index, :create, :update, :show, :delete]
  end
  resources :users

  # testing listings
  # resources :users do
  #   resources :listings
  # end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => "home#index"

end

app/models/user.rb
class User < ApplicationRecord
  # mount uploader like this?
  include Clearance::User
  mount_uploader :avatar, AvatarUploader
  enum role: [:customer, :host, :moderator, :superadmin]
  has_many :listings, dependent: :destroy
  has_many :reservations, dependent: :destroy
  has_many :authentications, dependent: :destroy
  def self.create_with_auth_and_hash(authentication, auth_hash)
    user = self.create!(
      full_name: auth_hash["info"]["name"],
      email: auth_hash["info"]["email"],
      password: SecureRandom.hex(10)
    )

    user.authentications << authentication
    return user
  end

  # grab google to access google for user data
  def google_token
    x = self.authentications.find_by(provider: 'google_oauth2')
    return x.token unless x.nil?
  end

  # uploader = AvatarUploader.new
  # uploader.store!(my_file)
  # uploader.retrieve_from_store!('my_file.png')
  #
  # u = User.new
  # u.avatar = params[:file] # Assign a file like this, or
  #
  # # like this
  # u.save!
  # u.avatar.url # => '/url/to/file.png'
  # u.avatar.current_path # => 'path/to/file.png'
  # u.avatar_identifier
end

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController
  def example
  end

  def index
    @user_profile = User.find(params[:id])
    @user_listing = Listing.where(user_id: params[:id])
    @user_id = User.find(current_user.id)
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
    @user_id = User.find(current_user.id)
  end

  def show
    @all_users = User.all
  end

  def admin
    @all_users = User.all
  end

  def profile
    @user_profile = User.find(params[:id])
    @user_listing = Listing.where(user_id: params[:id])
    @user_id = User.find(current_user.id)
    @customer_bookings = Reservation.where(user_id: params[:id])

  end

  def create

    @user = User.new(user_params)
    if @user.save
      sign_in @user
      redirect_back_or url_after_create
    else
      render template: "users/new"
    end
  end

  def update

    @user_id = User.find(current_user.id)
    @user = User.find(params[:id])
      if @user.update(user_params)
        redirect_to user_profile_path(current_user.id)
      else
        render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @listing = Listing.where(user_id: params[:id])
    @listing.destroy_all
    @user.destroy
    redirect_to root_path
  end

  def delete_avatar
    @user_profile = User.find(params[:id])
    @user_profile.remove_avatar!
    @user_profile.save
    redirect_to user_profile_path(current_user.id)
  end

  private
  def user_params
    params.require(:user).permit(:email, :password, :full_name, :role, :avatar, :gender, :phone, :country, :birthdate)
  end

end

app/helpers/user_helper.rb
module UserHelper
end

app/views/users/_form.html.erb
  <div id="clearance" class="form-group">
    <div class="login-popup-wrap new_login_popup">
      <div class="login-popup-heading text-center">
        <h2>Registration Form</h2>
          <div class="form-group text-center">
            <%= form.label :full_name %>
            <%= form.text_field :full_name, type: 'name', class: "form-control" %>
          </div>

          <div class="form-group text-center">
            <%= form.label :email %>
            <%= form.text_field :email, type: 'email', class: "form-control" %>
          </div>
          <div class="password-field text-center">
            <%= form.label :password %>
            <%= form.password_field :password, class: "form-control" %>
          </div>
          <div>
            <%= form.file_field :avatar %>
          </div>
            <%= form.submit class:"btn btn-primary login-popup-btn"%>
            <div class="text-center">
              Already have an account? <%= link_to "Sign In", sign_in_path %>
            </div>
        </div>
      </div>
    </div>

app/views/users/_navbar.html.erb
<div id="header">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="/">CoolStay</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <%= link_to 'Explore Now', controller: 'listings'%>
          </li>
          <li class="nav-item active">
            <%= link_to 'New listing', new_listing_path %>
          </li>
          <li class="nav-item active">
            <%= link_to 'My Profile', user_profile_path(current_user.id) %>
          </li>
          <li class="nav-item active">
            <%= link_to t(".sign_out"), sign_out_path, method: :delete %>
          </li>
        </ul>
      </div>
    </nav>
</div>

app/views/users/admin.html.erb
<%= render 'navbar' %>
<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th colspan="3"></th>
  </tr>

  <% @all_users.each do |user| %>
    <tr>
      <td><%= user.full_name %></td>
      <td><%= user.email %></td>
      <td><%= link_to 'Destroy', user_path(user),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
</table>

app/views/users/edit.html.erb
<%= render 'shared/navbar' %>

<div id="clearance" class="sign-up">

  <%= form_for @user do |form| %>

  <div id="clearance" class="form-group">
    <div class="login-popup-wrap new_login_popup">
      <div class="login-popup-heading text-center">
        <h2>Update Your Profile</h2>
          <div class="form-group text-center">
            <%= form.label :full_name %>
            <%= form.text_field :full_name, type: 'name', class: "form-control" %>
          </div>

          <div class="form-group text-center">
            <%= form.label :email %>
            <%= form.text_field :email, type: 'email', class: "form-control" %>
          </div>
          <div>
            <%= form.file_field  :avatar %>
          </div>
          <br>
            <%= form.submit class:"btn btn-primary"%>
            <%= link_to 'Back', root_path, class:"btn btn-secondary" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <%= form_for User.new do |form| %>
    <%= render partial: '/users/form', object: form %>
  <% end %>
</div>

app/views/users/profile.html.erb
<%= render partial: "shared/navbar" %>

  <div class="profile-image-container">
    <h4><%= @user_profile.full_name %></h4>
    <%= image_tag @user_profile.avatar.url, class: "profile-image" %>
    <%= form_for @user_profile, html: { multipart: true } do |f| %>
      <%= link_to 'Update Profile', edit_user_path(@user_id) %>|
      <%= link_to 'Delete', delete_avatar_path(@user_profile),
                  method: :post,
                  data: { confirm: 'Are you sure?' } %>
    <% end %>
</div>

<% if @user_listing.length != 0 %>
<h3>Your listing</h3>
<table class="listing_table">
  <tr>
    <th>Property</th>
    <th>Location</th>
    <th>Price</th>
    <th>Description</th>
    <th colspan="3">Action</th>
  </tr>

  <% @user_listing.each do |listing| %>
    <tr>
      <td><%= listing.property_title %></td>
      <td><%= listing.location %></td>
      <td>USD<%= listing.price %></td>
      <td><%= listing.description %></td>
      <td><%= link_to 'Details', listing_path(listing) %></td>
      <td><%= link_to 'Edit', edit_listing_path(listing) %></td>
          <td>
            <i class="fas fa-trash">
              <%= link_to 'Delete', listing_path(listing),
              method: :delete,
              data: { confirm: 'Are you sure?' } %>
            </i>
          </td>

    </tr>
    <% end %>
</table>
<% end %>


<br>



<% if @customer_bookings.length != 0 %>
<h3>Your listing</h3>
<table class="listing_table">
  <tr>
    <th>Listing ID</th>
    <th>Check In</th>
    <th>Check Out</th>
    <th>Total Payment</th>
    <th colspan="3">Action</th>
  </tr>

  <% @customer_bookings.each do |booking| %>
    <tr>
      <td><%= booking.listing_id %></td>
      <td><%= booking.start_date %></td>
      <td><%= booking.end_date %></td>
      <td>USD<%= booking.total_price %></td>
      <td><%= link_to 'Show', listing_reservation_path(booking.listing_id, booking.id) %></td>

    </tr>
    <% end %>
</table>
<% end %>

app/views/users/setting.html.erb
<!-- Your Account Setting -->

<!-- Edit Username -->
  <!-- update_username  -->

<!-- Edit Password -->
  <!-- old Password -->
  <!-- new Password -->
<!--reconfirm pass word  -->