config/routes.rb
Rails.application.routes.draw do
  get 'braintree/new'
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  get 'home/index'

  get 'listings/verify' => 'listings#verify', as: 'listing_pending_verification'
  post 'listings/:id/verify' => 'listings#verify!', as: 'verify_listing'
  post 'users/:id/delete_avatar' => 'users#delete_avatar', as: 'delete_avatar'
  post 'users/:id/upload_avatar' => 'users#upload_avatar', as: 'upload_avatar'
  post 'listings/:id/delete_photo' => 'listings#delete_photo', as: 'delete_photo'

  post 'listings/:listing_id/reservations/:id/payment' => 'braintree#checkout', as: 'checkout'
  get 'listings/:listing_id/reservations/:id/payment' => 'braintree#new', as: 'verify_payment'
  # get 'listings/:listing_id/reservations/:id/payment' => 'braintree#checkout', as: 'checkout'

  get 'users/:id/edit' => 'users#edit', as: 'edit_profile'
  get 'listings/:id/edit' => 'listings#edit', as: 'edit_listing'
  get "listings/search" => 'listings#search', as: 'listings_search'
  get "listings/global_search" => 'listings#global_search', as: 'global_search'
  get "listings/ajax_search" => 'listings#ajax_search', as: 'ajax_search'
  # get 'reservations/new'
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

    get "users/admin"
    get "users/profile"

    get "users/:id" => 'users#profile', as: 'user_profile'
    get "listings/confirmation" => 'listings#listing_confirmation', as: 'listing_confirmation'
    get "users/:id/delete" => 'users#destroy', as: 'delete_user'


  # get "users/:id/deletes"
  resources :articles
  resources :listings do
    # remvoed :index
    resources :reservations, only: [:index, :create, :update, :show, :delete]
  end
  resources :users

  # testing listings
  # resources :users do
  #   resources :listings
  # end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => "home#index"

end

app/views/shared/_listings.html.erb
<% @listings_page.each do |listing| %>
  <% if listing.verify == true %>
  <div class="card-deck grow1">
      <div class="card">
        <div class="card-body">
          <% if listing.photos[0] == nil %>
          <a href="/listings/<%=listing.id%>">
          <%= image_tag ("No_Image_Available.png"), :class => "card-img-top"%>
          </a>
          <% else -%>
          <a href="/listings/<%=listing.id%>">
          <%= image_tag listing.photos.first.url, :class => "card-img-top"%>
          </a>
          <% end %>
          <h5 class="card-title"><%= listing.property_title %></h5>
          <p class="card-text"><%= listing.location %></p>
          <p class="card-text">USD <%= listing.price %> per night</p>
          <%= link_to 'Details', listing_path(listing), class:"details-link" %>
        </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>
<div class="pagination">
<%= paginate @listings_page %>
</div>

app/views/shared/_navbar.html.erb
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="/">CoolStay</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <div class="whole-navbar">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active" >
                <%= form_for :listing, url: global_search_path, method: :get do |f| %>
                <%= f.text_field :term, list: "list", placeholder: "search field", class: "grow" %>
                <datalist id="list"></datalist>
                <!-- <i class="fas fa-search fa-lg" type="submit" value="" data-disable-with="false"></i> -->
                <button type="submit" class="btn btn-outline-secondary" data-disable-with="false">Search</button>
                <% end -%>
              </li>
              <li class="nav-item active">
                <a class="dropdown-item" href="/">About Us</a>
              </li>
              <li class="nav-item active">
                <a class="dropdown-item" href="/listings">Explore</a>
              </li>
              <li class="nav-item active">
                <a class="dropdown-item" href="/listings/new">New Listing</a>
              </li>
          <!-- Account Dropdown -->
            <li class="nav-item action">
              <div class="dropdown mx-2 profile-box">
                <a class="" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class="fas fa-user-circle fa-2x"></i>
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
                  <a class="dropdown-item" href="/users/<%=current_user.id%>">Your Profile</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="#">Invite Friends</a>
                  <a class="dropdown-item" href="/users/<%=current_user.id%>">Account Settings</a>
                  <div class="dropdown-divider"></div>
                  <%= link_to t(".sign_out"), sign_out_path, method: :delete, class:"dropdown-item"  %>
                </div>
              </div>
            </li>
              </div>
            </ul>
          </div>
        </div>
      </nav>

app/views/shared/_navbar_guest.html.erb
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="/">CoolStay</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="dropdown-item" href="/listings">Explore</a>
        </li>
        <li class="nav-item active">
          <a href="#" class="dropdown-item" data-toggle="modal" data-target="#at-login">Log In</a>
        </li>
        <li class="nav-item active">
          <a href="#" class="dropdown-item" data-toggle="modal" data-target="#at-signup">Sign Up</a>
        </li>
      </ul>
    </div>
  </nav>

  <!--  Modals for signup / signin -->
  <div class="col-md-12">
    <section class="at-login-form">
      <!-- MODAL LOGIN -->
      <div class="modal fade" id="at-login" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="">
                <span aria-hidden="true">×</span>
              </button>
            </div>
            <div class="modal-body">
              <!--   RENDERED FORM -->
              <%= render template: "sessions/new" %>
              <div class="row">
                <div class="col-md-6">
                  <div class="checkbox">
                    <label>
                      <input type="checkbox"> Remember me
                    </label>
                    <p class="frgt-pswd"   data-toggle="modal" data-dismiss="modal"  data-target="#at-reset-pswd">Forgot Password?</p>
                  </div>
                </div>
              </div>
            </div>
          </div><!--   MODAL CONTENT ENDS -->
        </div>  <!--  MODAL DIALOG ENDS -->
      </div>  <!-- MODAL LOGIN ENDS -->

      <!-- MODAL SIGNUP -->
      <div class="modal fade" id="at-signup" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
            </div>
            <div class="modal-body">
              <%= render template: "users/new" %>
            </div>
            <div class="modal-footer">
            </div>
          </div>
        </div>  <!-- MODAL DIALOG ENDS -->
      </div> <!-- MODAL SIGNUP ENDS -->

      <!-- MODAL SIGNUP FORM FILLING -->
      <div class="modal fade" id="at-signup-filling" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">×</span>
              </button>
            </div>
            <div class="modal-body">
              <p>Sign up with
                <a href="#">Facebook</a> <br>
                <br>
                <a href="#">Google</a>
              </p>
              <div class="signup-or-separator">
                <span class="h6 signup-or-separator--text">or
                </span><hr>
              </div>
              <!--  RENDERED FORM -->
              <%= render template: "users/new" %>

              <div class="row">
                <div class="col-md-12">
                  <div class="checkbox">
                    <label>
                      <input type="checkbox">
                      I’d like to receive coupons and inspiration
                    </label>
                  </div>
                  <p>By signing up, I agree to CoolStay’s , Payments <a href="#">Terms of Service</a>, <a href="#">Privacy Policy</a>, <a href="#">Guest Refund Policy</a>, and <a href="#">Host Guarantee Terms</a>. </p>
                </div>
              </div>
            </div>
            <div class="modal-footer">
              <div class="row">
                <div class="col-md-6">
                  <p class="ta-l">Already a Member? </p>
                </div>
                <div class="col-md-4 col-md-offset-2">
                  <button class="btn-gst"  data-toggle="modal"  data-dismiss="modal" data-target="#at-login">Login</button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div> <!-- MODAL SIGNUP FORM FILLING ENDS -->

      <!-- MODAL FORGOT PASSWORD -->
      <div class="modal fade" id="at-reset-pswd" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
            </div>
            <div class="modal-body">
              <form>
                <p> Enter the email address associated with your account, and we’ll email you a link to reset your password. </p>
                <div class="form-group">

                  <input type="email" class="form-control-form " placeholder="Email">
                </div>
              </form>
            </div>
            <div class="modal-footer">
            </div>
          </div>
        </div>
      </div> <!-- MODAL FORGOT PASSWORD ENDS -->

      <!-- MODAL HELP -->
      <div class="modal fade" id="at-helping" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
            </div>
            <div class="modal-body">
              <form>
                <div class="form-group">
                  <input type="text" class="form-control-form "  placeholder="Enter Your Searches ">
                </div>
              </form>
            </div>
            <div class="modal-footer">
              <div class="row">
                <button class="btn-gst"  data-toggle="modal"  data-dismiss="modal" >Send a reset Link</button>
              </div>
            </div>
          </div>
        </div>
      </div> <!-- MODAL HELP ENDS -->
    </section>
  </div>

app/views/shared/_navbar_no_search.html.erb
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="/">CoolStay</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="dropdown-item" href="/">Home</a>
            </li>
            </div>
          </ul>
        </div>
      </nav>