config/routes.rb
Rails.application.routes.draw do
  get 'braintree/new'
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  get 'home/index'

  get 'listings/verify' => 'listings#verify', as: 'listing_pending_verification'
  post 'listings/:id/verify' => 'listings#verify!', as: 'verify_listing'
  post 'users/:id/delete_avatar' => 'users#delete_avatar', as: 'delete_avatar'
  post 'users/:id/upload_avatar' => 'users#upload_avatar', as: 'upload_avatar'
  post 'listings/:id/delete_photo' => 'listings#delete_photo', as: 'delete_photo'

  post 'listings/:listing_id/reservations/:id/payment' => 'braintree#checkout', as: 'checkout'
  get 'listings/:listing_id/reservations/:id/payment' => 'braintree#new', as: 'verify_payment'
  # get 'listings/:listing_id/reservations/:id/payment' => 'braintree#checkout', as: 'checkout'

  get 'users/:id/edit' => 'users#edit', as: 'edit_profile'
  get 'listings/:id/edit' => 'listings#edit', as: 'edit_listing'
  get "listings/search" => 'listings#search', as: 'listings_search'
  get "listings/global_search" => 'listings#global_search', as: 'global_search'
  get "listings/ajax_search" => 'listings#ajax_search', as: 'ajax_search'
  # get 'reservations/new'
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

    get "users/admin"
    get "users/profile"

    get "users/:id" => 'users#profile', as: 'user_profile'
    get "listings/confirmation" => 'listings#listing_confirmation', as: 'listing_confirmation'
    get "users/:id/delete" => 'users#destroy', as: 'delete_user'


  # get "users/:id/deletes"
  resources :articles
  resources :listings do
    # remvoed :index
    resources :reservations, only: [:index, :create, :update, :show, :delete]
  end
  resources :users

  # testing listings
  # resources :users do
  #   resources :listings
  # end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => "home#index"

end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :listing
  validates :start_date, presence: true
  validates :end_date, presence: true


  validate :reserved_date, if: -> { start_date && end_date }
  validate :check_dates, if: -> { start_date && end_date }
  # test scoping for filtering
  scope :property_title, -> (property_title) { where property_title: property_title }
  scope :location, -> (location) { where location: location }
  # scope :state, -> (state) { where state: state }
  # scope :price, -> (price) { where price: price }



  before_create :compute_total

  def check_dates
    if self.start_date > self.end_date
      errors.add(:Date, "Check-in cannot be later than check-out")
    end
  end

  def compute_total
    daily_rate = Listing.find(self.listing_id).price
    self.total_price = (self.end_date - self.start_date)*daily_rate.to_i
  end

  def reserved_date
    existing_reserve = Reservation.where(listing_id: self.listing_id) #array of reservations

    # unavailable_date = current_listing
    start_date = self.start_date
    end_date = self.end_date
    # reserved = (start_date...end_date).to_a

    # iterate over array of date

    existing_reserve.each do |x|
      # byebug
      all_reserved = x.start_date..x.end_date
      if ((start_date.to_date..end_date.to_date).overlaps?all_reserved) && x != self
        errors.add(:Property, "not available at the selected date. Please try other date")
        break
      end
    end
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  def index
    @user_id = User.find(current_user.id)
  end

  def show
    @reservation = Reservation.find(params[:id])
    @listing = Listing.find(params[:listing_id])
  end

  def new
    @user = current_user
    @reservation = Reservation.new
    @user_id = User.find(current_user.id)
  end

  def create
    details = reservation_params
    details[:start_date] = Date.strptime(reservation_params[:start_date], '%m/%d/%Y') if reservation_params[:start_date] != ""
    details[:end_date] = Date.strptime(reservation_params[:end_date], '%m/%d/%Y') if reservation_params[:end_date] != ""
    @reservation = Reservation.new(details)
    if current_user != nil
      @reservation.user_id = current_user.id
    end
    @reservation.listing_id = params[:listing_id]
    # @user = User.find(@reservation.user_id)
    @listing = Listing.find(params[:listing_id])
    @host = User.find(@listing.user_id)

    if @reservation.save
      redirect_to listing_reservation_path(@reservation.listing_id,@reservation.id) #reservations/:id
      @message = ""
    end
  end

  private
    def reservation_params
      params.require(:reservation).permit(:start_date, :end_date, :remark, :user_id, :listing_id, :total_price, :payment_status)
    end

end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/index.html.erb
<h1>Index Page for Reservation</h1>

app/views/reservations/new.html.erb
<p>
  <strong>Property name:</strong>
  <%= @listing.property_title %>
</p>

<p>
  <strong>Price:</strong>
  <%= @listing.price %>
</p>
<p>
  <strong>Location:</strong>
  <%= @listing.location %>
</p>
<p>
  <strong>description:</strong>
  <%= @listing.description %>
</p>

<p>
  <strong>Host:</strong>
  <%= @user.full_name %>
</p>

<%= form_with model: @listing, local: true do |form| %>
  <%= form.text_field :start_date, {class: 'datepicker', placeholder:'Check-in'} %>
  <script type="text/javascript">
    $(document).ready(function(){
      $('.datepicker').datepicker();
    });
  </script>
  <input type="text" class='datepicker' placeholder="Check-out" >
  <script type="text/javascript">
    $(document).ready(function(){
      $('.datepicker').datepicker();
    });
  </script>
  <p>
    <%= form.submit %>
  </p>
<% end %>

<%= link_to 'Back', listings_path %>

app/views/reservations/show.html.erb
<h2>Your booking is confirmed</h2>
<h3>Kindly refer to details as below:-</h3>

<p><strong>Property name:</strong> <%= @listing.property_title %></p>
<p><strong>Check In:</strong> <%= @reservation.start_date %></p>
<p><strong>Check Out:</strong> <%= @reservation.end_date %></p>
<p><strong>Daily Rate: RM</strong> <%= @listing.price %></p>
<p><strong>Total Amount: RM</strong> <%= @reservation.total_price %></p>
<p><strong>Description</strong> <%= @listing.description %></p>
<p><strong>Bed Number</strong> <%= @listing.bed_number %></p>
<p><strong>Guest Number</strong> <%= @listing.guest_number %></p>
 
<% if @reservation.payment_status != true %>
  <br>
  <%= link_to 'Pay Now', verify_payment_path(@listing, @reservation), data: { turbolinks: false } %>
<% end -%>